import { Task, Priority, TaskStatus, RepeatInterval } from '../types/task';

// ─── Sample Tasks (seeded with a fixed userId placeholder) ───────────────────

export const SAMPLE_USER_ID = 'sample_user_001';

export const DUMMY_TASKS: Omit<Task, 'userId'>[] = [
  {
    id: 'task_001',
    title: 'Complete Q3 project proposal',
    description: 'Write a detailed proposal for the new client project including timeline, budget, and resource allocation.',
    category: 'work',
    priority: Priority.CRITICAL,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    dueTime: '17:00',
    reminder: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000 - 30 * 60 * 1000),
    repeat: RepeatInterval.NONE,
    completed: false,
    completedAt: null,
    color: '#ef4444',
    attachments: [],
    notes: 'Make sure to include case studies from similar projects.',
    tags: ['work', 'project', 'urgent'],
    estimatedTime: 120,
    isFavorite: true,
    order: 0,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_002',
    title: 'Morning workout',
    description: '45-minute cardio + strength training session.',
    category: 'health',
    priority: Priority.HIGH,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(),
    dueTime: '07:00',
    reminder: null,
    repeat: RepeatInterval.DAILY,
    completed: false,
    completedAt: null,
    color: '#22c55e',
    attachments: [],
    notes: '',
    tags: ['fitness', 'routine'],
    estimatedTime: 45,
    isFavorite: false,
    order: 1,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_003',
    title: 'Read "Atomic Habits"',
    description: 'Finish chapters 8-12 and take notes on key concepts.',
    category: 'study',
    priority: Priority.MEDIUM,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    dueTime: null,
    reminder: null,
    repeat: RepeatInterval.NONE,
    completed: false,
    completedAt: null,
    color: '#06b6d4',
    attachments: [],
    notes: 'Focus on the habit loop and identity-based habits.',
    tags: ['reading', 'self-improvement'],
    estimatedTime: 90,
    isFavorite: true,
    order: 2,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_004',
    title: 'Grocery shopping',
    description: 'Buy vegetables, fruits, dairy, and cleaning supplies.',
    category: 'shopping',
    priority: Priority.MEDIUM,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(),
    dueTime: '11:00',
    reminder: null,
    repeat: RepeatInterval.WEEKLY,
    completed: false,
    completedAt: null,
    color: '#f59e0b',
    attachments: [],
    notes: 'Check if we need coffee and yogurt.',
    tags: ['shopping', 'weekly'],
    estimatedTime: 60,
    isFavorite: false,
    order: 3,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_005',
    title: 'Review monthly budget',
    description: 'Analyze spending patterns and adjust budget for next month.',
    category: 'finance',
    priority: Priority.HIGH,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    dueTime: '20:00',
    reminder: null,
    repeat: RepeatInterval.MONTHLY,
    completed: false,
    completedAt: null,
    color: '#10b981',
    attachments: [],
    notes: '',
    tags: ['finance', 'planning'],
    estimatedTime: 30,
    isFavorite: false,
    order: 4,
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_006',
    title: 'Design new app icon',
    description: 'Create icon variants for iOS and Android following platform guidelines.',
    category: 'work',
    priority: Priority.MEDIUM,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    dueTime: null,
    reminder: null,
    repeat: RepeatInterval.NONE,
    completed: false,
    completedAt: null,
    color: '#8b5cf6',
    attachments: [],
    notes: 'Use brand colors and ensure readability at small sizes.',
    tags: ['design', 'mobile'],
    estimatedTime: 180,
    isFavorite: false,
    order: 5,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_007',
    title: 'Doctor appointment',
    description: 'Annual health check-up at City Medical Center.',
    category: 'health',
    priority: Priority.HIGH,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    dueTime: '10:30',
    reminder: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000),
    repeat: RepeatInterval.NONE,
    completed: false,
    completedAt: null,
    color: '#ec4899',
    attachments: [],
    notes: 'Remember to bring previous lab reports.',
    tags: ['health', 'appointment'],
    estimatedTime: 90,
    isFavorite: false,
    order: 6,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_008',
    title: 'Plan weekend trip to Goa',
    description: 'Research hotels, book flights, plan day-by-day itinerary.',
    category: 'travel',
    priority: Priority.LOW,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    dueTime: null,
    reminder: null,
    repeat: RepeatInterval.NONE,
    completed: false,
    completedAt: null,
    color: '#f97316',
    attachments: [],
    notes: 'Look for beachside resorts and watersports activities.',
    tags: ['travel', 'weekend', 'fun'],
    estimatedTime: 120,
    isFavorite: true,
    order: 7,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_009',
    title: 'Complete React Native course',
    description: 'Finish sections 15–20 on advanced topics and animations.',
    category: 'study',
    priority: Priority.HIGH,
    status: TaskStatus.COMPLETED,
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    dueTime: null,
    reminder: null,
    repeat: RepeatInterval.NONE,
    completed: true,
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    color: '#3b82f6',
    attachments: [],
    notes: '',
    tags: ['learning', 'coding', 'react-native'],
    estimatedTime: 240,
    actualTime: 210,
    isFavorite: false,
    order: 8,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_010',
    title: 'Team standup meeting',
    description: 'Daily standup at 9 AM. Prepare update on ongoing tasks.',
    category: 'work',
    priority: Priority.MEDIUM,
    status: TaskStatus.COMPLETED,
    dueDate: new Date(Date.now() - 2 * 60 * 60 * 1000),
    dueTime: '09:00',
    reminder: null,
    repeat: RepeatInterval.DAILY,
    completed: true,
    completedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    color: '#3b82f6',
    attachments: [],
    notes: '',
    tags: ['meeting', 'work'],
    estimatedTime: 15,
    actualTime: 20,
    isFavorite: false,
    order: 9,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'task_011',
    title: 'Update LinkedIn profile',
    description: 'Add new skills, certifications and update work experience section.',
    category: 'personal',
    priority: Priority.LOW,
    status: TaskStatus.ACTIVE,
    dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    dueTime: null,
    reminder: null,
    repeat: RepeatInterval.NONE,
    completed: false,
    completedAt: null,
    color: '#6366f1',
    attachments: [],
    notes: '',
    tags: ['career', 'networking'],
    estimatedTime: 45,
    isFavorite: false,
    order: 10,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'task_012',
    title: 'Meditate for 15 minutes',
    description: 'Morning mindfulness session using guided meditation app.',
    category: 'health',
    priority: Priority.MEDIUM,
    status: TaskStatus.COMPLETED,
    dueDate: new Date(),
    dueTime: '06:30',
    reminder: null,
    repeat: RepeatInterval.DAILY,
    completed: true,
    completedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    color: '#14b8a6',
    attachments: [],
    notes: '',
    tags: ['mindfulness', 'routine'],
    estimatedTime: 15,
    actualTime: 15,
    isFavorite: false,
    order: 11,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
];
